# Use official Python image
FROM python:3.9

# Set working directory inside container
WORKDIR /app

# Copy all project files into the container
COPY . .

# Install dependencies
RUN pip3 install -r requirements.txt

# Run the application
CMD ["python", "app/app.py"]
