# Use official Python image
FROM python:3.9

# Set working directory inside container
WORKDIR /app

# Copy all project files into the container
COPY . .



# Run the application
CMD ["python", "app/app.py"]
